import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { NextAppDirEmotionCacheProvider} from 'tss-react/next/appDir';
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head></head>
      <body className={inter.className}>
        <NextAppDirEmotionCacheProvider options={{key: "css"}}>
          {children}
        </NextAppDirEmotionCacheProvider>
      </body>
    </html>
  )
}
